apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-feed
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - image: congdinh2012/udagram-api-feed
          name: backend-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1000Mi"
              cpu: "250m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
            - secretRef:
                name: aws-secret
      restartPolicy: Always
