apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: <cat ~/.aws/credentials | base64 - use command to get base64 credentials>
  AWS_ACCESS_KEY_ID: <base64 access key - optional>
  AWS_SECRET_ACCESS_KEY: <base64 secret access key - optional>